nelmio_cors:
    defaults: ~
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST', 'GET']
            allow_headers: ['Content-Type']
            origin_regex: true
