version: '3'
services:
    adminer:
        ports:
            - '8081:8080'
        image: 'adminer:latest'
    mysql:
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=db_name
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        image: 'mysql:5.7'
    php:
        volumes:
            - './:/usr/share/nginx/html'
        build: 'docker/php'
    nginx:
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=public
        image: 'okty/nginx:1.14'
